// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("SEARCH-BAR.html", "XoXo", " ", "");
   this[database_length++] = new SearchPage("Alde.html", "XoXo", "HELLO, I'M  CHARIES  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque ALDE   ", "");
   this[database_length++] = new SearchPage("Baclay.html", "XoXo", "HELLO, I'M  EDZEL   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque BACLAY   ", "");
   this[database_length++] = new SearchPage("Bonghanoy.html", "XoXo", "HELLO, I'M  KRISTINE   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque BONGHANOY   ", "");
   this[database_length++] = new SearchPage("Camacho.html", "XoXo", "HELLO, I'M  MERRY JEAN  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque CAMACHO   ", "");
   this[database_length++] = new SearchPage("Daño.html", "XoXo", "HELLO, I'M  JHON CARLO  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque DAÑO   ", "");
   this[database_length++] = new SearchPage("Despi.html", "XoXo", "HELLO, I'M  KESSEL DESPI  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque DESPI   ", "");
   this[database_length++] = new SearchPage("Fernandez.html", "XoXo", "HELLO, I'M  FABIAN BLAKE  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque FERNANDEZ   ", "");
   this[database_length++] = new SearchPage("Gordillo.html", "XoXo", "HELLO, I'M  MARC JOSEPH  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque GORDILLO   ", "");
   this[database_length++] = new SearchPage("Indig.html", "XoXo", "HELLO, I'M  RICA  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque INDIG   ", "");
   this[database_length++] = new SearchPage("Osabel.html", "XoXo", "HELLO, I'M  KATE ALEXIS  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque OSABEL   ", "");
   this[database_length++] = new SearchPage("Panilag.html", "XoXo", "HELLO, I'M  JOHN ELMER  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque PANILAG   ", "");
   this[database_length++] = new SearchPage("Parawan.html", "XoXo", "HELLO, I'M  ARIANNE  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque PARAWAN   ", "");
   this[database_length++] = new SearchPage("Ruben.html", "XoXo", "HELLO, I'M  MERZI MARIE  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque RUBEN   ", "");
   this[database_length++] = new SearchPage("Sanoy.html", "XoXo", "HELLO, I'M  SHEILA MAE  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque SANOY   ", "");
   this[database_length++] = new SearchPage("Sevilla.html", "XoXo", "HELLO, I'M  CRISTINA  Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus   Lorem ipsum dolor sit amet, consectetur adipiscing elit Duis pharetra fermentum eros non maximus Cras posuere diam vel augue consequat vulputate Nulla lacus augue, vestibulum et porttitor non, aliquam sit amet lectus Donec nec dapibus felis, vitae bibendum magna Cras semper interdum nulla eget pellentesque SEVILLA   ", "");
   this[database_length++] = new SearchPage("Home.html", "XoXo", "Hello, my name is Cristina  Sevilla  I'm a   I'm a Graphic Designer Student with a three years course in CTU-Main My expertise is to create, design and many more  Graphics Designer   ", "");
   this[database_length++] = new SearchPage("About.html", "XoXo", "I'm Cristina Sevilla a Graphics Designer  I am a strongly seasoned and hardworking Entry-Level Graphic Designer with extraordinary creative thinking and project design abilities Adept multitasker with the ability to bring simultaneous graphic design projects to completion with complete efficiency and accuracy Able to work well independently or as a member of a professional graphic design team  Birthday  October 4, 2001  Website  www.github.com  Degree  BSGD  City  Cebu  Age  21  Email  mysticmsgr04@gmail.com  Phone  +639 632 715 200  Freelance  Available  MediBang  93%  66%  Photoshop  96%  Canva  85%  AutoCAD  About   ", "");
   this[database_length++] = new SearchPage("Services.html", "XoXo", "Services  Ibis Paint  MediBang Pro  Canva  Krita  Manual Art  AutoCad  Web Design  Has all the features you need to seamlessly create manga and illustrations   Is a FREE digital painting and comic creation software   Global multi-national graphic design platform that is used to create social media graphics and presentations  For creating a website that focuses on aesthetic factors like layout, user interface and other  To create 2D and 3D drawings and models, electrical diagrams, construction drawings, and more  Is a free and open-source raster graphics editor designed primarily for digital art and 2D animation  Use various aesthetic experiences like carving, painting, photography, and other related crafts  Graphic Design  The art and practice of planning and projecting ideas and experiences with visual and textual content   ", "");
   this[database_length++] = new SearchPage("Portfolio.html", "XoXo", "Portfolio  My Last Projects    ", "");
   this[database_length++] = new SearchPage("Contact.html", "XoXo", "Contact Me  DO YOU HAVE ANY QUESTIONS?  Call Us On  Office  Email  Website  I'm At Your Service  +639632715200  CTU-Main  mysticmsgr04@gmail.com  www.github.com  SEND ME AN EMAIL  I'M VERY RESPONSIVE TO MESSAGES   ", "");
   this[database_length++] = new SearchPage("OK.html", "XoXo", "Contact Me  DO YOU HAVE ANY QUESTIONS?  Call Us On  Office  Email  Website  I'm At Your Service  +639632715200  CTU-Main  mysticmsgr04@gmail.com  www.github.com  SEND ME AN EMAIL  I'M VERY RESPONSIVE TO MESSAGES  THANK YOU! YOUR MESSAGE HAS  BEEN SENT!   ", "");
   return this;
}
